name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake zlib1g-dev python3-dev

      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip # Standard pip cache directory
          # Key for the cache. If you add a requirements.txt, this will use its hash.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Pybind11 for C++ build
        run: |
          python3 -m pip install --upgrade pip
          pip install pybind11 # Installs pybind11, making headers available

      - name: Cache C++ build artifacts
        id: cache-cpp-build
        uses: actions/cache@v4
        with:
          path: c++/build # Directory to cache
          # Key for the cache. Changes if C++ source/CMake files change.
          key: ${{ runner.os }}-cpp-build-${{ hashFiles('c++/CMakeLists.txt', 'c++/src/**', 'c++/include/**') }}
          restore-keys: |
            ${{ runner.os }}-cpp-build-

      - name: Build C++ project
        run: |
          cd c++
          # Get the CMake directory for pybind11 installed via pip
          PYBIND11_CMAKE_DIR=$(python3 -m pybind11 --cmakedir)
          # Pass this directory to CMake to help it find pybind11Config.cmake or pybind11-config.cmake
          cmake -B build -Dpybind11_DIR=${PYBIND11_CMAKE_DIR} 
          cd build
          make

      - name: Install other Python dependencies
        run: |
          # pip and pybind11 are already installed/upgraded
          pip install open3d # Will use cached packages if available
          
      - name: Run Python scripts
        run: |
          python3 minuet_trace.py --config ./config.json
          # Ensure the trace file from the C++ version is used if that's intended
          # For now, assuming map_trace.bin.gz is from the python script run
          python3 map_trace_reader.py --trace-file out/map_trace.bin.gz --filter-phase "LKP"